### PR TITLE
Add pixelmap interactivity

### PR DESCRIPTION
**Pull request by naglepuff**
Depends on [large_image #794](https://github.com/girder/large_image/pull/794). To test these changes before that is merged and released, you will need to build large image from that branch to use with your instance of HUI.

This PR allows users to interact with pixelmap annotations in HistomicsUI. In order to test these changes you can generate a pixelmap for a large image using the [Superpixel Segmentation script in HistomicsTK](https://github.com/DigitalSlideArchive/HistomicsTK/pull/925).

**Adding Categories**
In the draw widget, you can see elements for the currently selected annotation. Next to any pixelmap element is now a plus (+) icon. Clicking this icon will allow you to add categories to the pixelmap annotation. Each category added this way will also create a corresponding style group. The form to create a category requires a label and fill color. Additionally, if the pixelmap annotation contains boundary regions, a stroke color will be required by the validation logic.

**Editing Superpixels via the Draw Widget**
There are a couple of ways to change superpixel colors. The first is available if the currently selected style in the draw widget corresponds to a category of the pixelmap you want to edit. Such styles will have an ID of the form `<elementId>-<categoryIndex>-<categoryLabel>`. With this condition met, you can left click on a superpixel to change its category. You can hold shift + left click to enable painting with the currently selected category.

**Editing via the Context Menu**
Right-clicking a pixelmap element will bring up a context menu with a list of all available categories for that element. Selecting a category from the list will change the color of the superpixel.

Still to do:

- [x] Unit tests

### CODE REVIEW

**Comment by manthey** [comment]
I wonder if it would be better to reuse the existing style groups for categories, rather than explicitly define new one for each pixelmap.  That is, I already have categories "default", "glomeruli", and "interstitial" which have some colors defined.  Based purely on name matching, if such styles already exist, we could use the defined fill and stroke colors of those rather than what is explicitly stored with the pixelmap's categories.  If the pixelmap has a named category not defined, we would define a new general style group (rather than "annotation id-group name", just "group name").

If we think we should have distinct groups for each pixel map, then we should name them with the annotation name rather than the annotation id.

**Comment by manthey** [comment]
I created a new pixelmap using the superpixels algorithm, selected it as an annotation, defined a new class, and then tried to click on the pixelmap.  The context menu shows Default and my new class, but when I select the new class, I get a javascript error:
```
Cannot read properties of undefined (reading 'fillColor')
    at webgl_pixelmapFeature.color (geojs.js:161:58)
    at webgl_pixelmapFeature.out (<anonymous>:9361:49)
    at webgl_pixelmapFeature._computePixelmap (<anonymous>:41648:47)
    at webgl_pixelmapFeature._build (<anonymous>:22525:14)
    at webgl_pixelmapFeature._update (<anonymous>:22411:14)
    at webgl_pixelmapFeature.draw (<anonymous>:41462:14)
    at child._handlePixelmapContextMenu (ImageView.js:775:78)
    at triggerEvents (backbone.js:337:1)
    at triggerApi (backbone.js:322:1)
    at eventsApi (backbone.js:110:1)
color @ geojs.js:161
out @ VM495:9361
_computePixelmap @ VM495:41648
_build @ VM495:22525
_update @ VM495:22411
draw @ VM495:41462
_handlePixelmapContextMenu @ ImageView.js:775
triggerEvents @ backbone.js:337
triggerApi @ backbone.js:322
eventsApi @ backbone.js:110
Events.trigger @ backbone.js:312
_setCategory @ PixelmapContextMenu.js:35
dispatch @ jquery.js:5429
elemData.handle @ jquery.js:5233
```

This seems fairly repeatable.

Further, when I deselect the annotation, then clicking gets a different trackback:
```
VM495:21767 Event handler for geo_feature_mouseover threw an error TypeError: Cannot read properties of null (reading 'elements')
    at child.mouseOverOverlay (ImageView.js:828:67)
    at triggerEvents (backbone.js:337:1)
    at triggerApi (backbone.js:322:1)
    at eventsApi (backbone.js:110:1)
    at child.Events.trigger (backbone.js:312:1)
    at child._onMouseFeature (geojs.js:823:26)
    at webgl_pixelmapFeature.<anonymous> (geojs.js:407:39)
    at <anonymous>:21765:19
    at Array.forEach (<anonymous>)
    at webgl_pixelmapFeature.geoTrigger (<anonymous>:21763:30)
```

**Comment by naglepuff** [comment]
> I created a new pixelmap using the superpixels algorithm, selected it as an annotation, defined a new class, and then tried to click on the pixelmap. The context menu shows Default and my new class, but when I select the new class, I get a javascript error:

It seems that this error is because the pixelmap layer doesn't know about the new category. Now the layer is redrawn when the category is added. (7eb9106)

> Further, when I deselect the annotation, then clicking gets a different trackback:

Fixed in 1a5f2e1 by checking `this.activeAnnotation` before checking `this.activeAnnotation.elements()`.

**Comment by manthey** [comment]
Maybe this belongs in a follow-up PR.  If I change the color of a style (by selecting the <id>-<index>-<name> group in the Draw panel and then selecting the gear), it records the change I made in the sense that it saves the colors, but it doesn't apply the changed colors to the pixelmap (nor does it apply them going forward).

Similarly, we probably revisit the Edit Annotation dialog for this (and for other annotation types like heatmaps) so that it only shows sensible choices -- if we can't change the colors via the Edit Annotation dialog, they shouldn't be shown.

**Comment by naglepuff** [comment]
> Maybe this belongs in a follow-up PR. If I change the color of a style (by selecting the -- group in the Draw panel and then selecting the gear), it records the change I made in the sense that it saves the colors, but it doesn't apply the changed colors to the pixelmap (nor does it apply them going forward).

I think this is a relatively straightforward change. I'll explore it today and try to get a fix in. There should be some logic in place such that the style ID is read-only if it matches up with a pixelmap category. (or, even better, only the label part is editable)

> Similarly, we probably revisit the Edit Annotation dialog for this (and for other annotation types like heatmaps) so that it only shows sensible choices -- if we can't change the colors via the Edit Annotation dialog, they shouldn't be shown.

What if we were to change "Reset the style for all elements in this annotation" to "Reset the style for all *point, line, polyline* elements in this annotation?" We could still omit that section entirely if no elements of those types exist on the annotation being edited.

Reflecting on this, I think that overloading the meaning of "style group" here to also include pixelmap category is questionable, and leads to a lot of edge cases. I wasn't sure of a better way to represent this concept with the current framework. Basically what I was trying to achieve was the ability to select some category as the "Active" one, and this would inform left click/mouse over actions for rendered pixelmaps. 

I think having this functionality is useful, but maybe using the style groups to drive this wasn't the best idea. Maybe a different mechanism for designating some category as "active" would be better than using style groups. However, I'm not sure at the moment what that might look like.

**Comment by manthey** [comment]
> What if we were to change "Reset the style for all elements in this annotation" to "Reset the style for all _point, line, polyline_ elements in this annotation?" We could still omit that section entirely if no elements of those types exist on the annotation being edited.

Yes, that would work -- though I'd probably use `polygon` in favor of `polyline`, since we do elsewhere.

My thought on style groups is that they could very well have conceptual overlap between the ones in a pixelmap and the ones on other elements -- both could indicate that a region is a nucleus or glomeruli.  We probably want to show what we have to @cooperlab and get his opinion on what would make sense.

**Comment by cooperlab** [comment]
> > What if we were to change "Reset the style for all elements in this annotation" to "Reset the style for all _point, line, polyline_ elements in this annotation?" We could still omit that section entirely if no elements of those types exist on the annotation being edited.
> 
> Yes, that would work -- though I'd probably use `polygon` in favor of `polyline`, since we do elsewhere.
> 
> My thought on style groups is that they could very well have conceptual overlap between the ones in a pixelmap and the ones on other elements -- both could indicate that a region is a nucleus or glomeruli. We probably want to show what we have to @cooperlab and get his opinion on what would make sense.

Let's discuss this Friday. Jeff will be out but his feedback next week will be helpful too.

**Comment by naglepuff** [comment]
> I just deleted a pixelmap from the annotation panel, and the style groups for it didn't go away, so there is probably an edge case that isn't being handled.

Thanks for bringing this up. I can take a look at addressing this. It looks like we'd also have to check to see if any other annotations use that group before deleting it, since those pixelmap-specific style groups can also be applied to other elements across annotations.

**Comment by manthey** [comment]
I have a pixelmap and a regular annotation layer visible.  Some of the regular annotations overlap the pixelmap.  I click for a context menu, I get both the pixelmap AND the annotation context menus at the same time, overlapping.  Further, the pixelmap groups are in the annotation context menu where, as long as we are treating them as separate, they shouldn't apply.

**Comment by naglepuff** [comment]
The most recent batch of updates changes the new workflows for editing pixelmaps in HistomicsUI.

**Editing Pixelmaps**
Right clicking on a pixelmap will bring up a context menu, allowing you to choose any style group available. Selecting a style group will change the style of the clicked region on the pixelmap. Additionally, if you select an annotation containing a pixelmap element from the Annotations widget, you can left click a pixelmap to assign the currently selected style in the draw widget. Similarly you can shift + right click + drag to paint. This is similar to the original design, but you are no longer limited to specific style groups.

**Adding a new category**
The dialog to add a category to a specific pixelmap has been removed. Pixelmap categories are synchronized with available style groups. Adding a new style group to the draw widget will update pixelmaps that are already drawn. Pixelmaps not yet rendered will synchronize categories when they are rendered.

**Deleting a category**
Deleting a category via the edit style groups dialog will find and delete the corresponding category from pixelmap elements.

**Comment by manthey** [comment]
There was an obvious improvement in GeoJS that speeds up the initial pixelmap layer creation when the number of distinct superpixels is large.

**Comment by manthey** [comment]
We may want to merge and resolve some minor issues in a subsequent PR. 

If I open the style dialog and delete a style, and then cancel the style dialog, the style has still been deleted from the pixelmap.  For instance, I have a pixel map where I made styles called Blue, Green, Yellow and marked superpixels with each label.  I then open the dialog, delete Blue, but then cancel the dialog.  For other annotations, this doesn't actually delete the Blue style/group from the annotation, it just removes it from the selectable list.  Editing the annotation (e.g., a polygon), you'll see the group is still "Blue", though blue is no longer selectable from the menu.

I'm not sure what the principle of least surprise should dictate -- it seems like deleting a style certainly should affect annotations not being edited.  But if it is being edited, maybe this should have a warning or option -- either way, if we DO delete the style from the annotation, it needs to revert when we cancel the dialog.

**Comment by naglepuff** [comment]
> We may want to merge and resolve some minor issues in a subsequent PR.

I'm fine with this approach.

> If I open the style dialog and delete a style, and then cancel the style dialog, the style has still been deleted from the pixelmap. For instance, I have a pixel map where I made styles called Blue, Green, Yellow and marked superpixels with each label. I then open the dialog, delete Blue, but then cancel the dialog. For other annotations, this doesn't actually delete the Blue style/group from the annotation, it just removes it from the selectable list. Editing the annotation (e.g., a polygon), you'll see the group is still "Blue", though blue is no longer selectable from the menu.

> I'm not sure what the principle of least surprise should dictate -- it seems like deleting a style certainly should affect annotations not being edited. But if it is being edited, maybe this should have a warning or option -- either way, if we DO delete the style from the annotation, it needs to revert when we cancel the dialog.

Does 819066f address this issue in a sufficient manner? Deleting the categories no occurs after the user submits the form.

**Comment by manthey** [comment]
https://github.com/DigitalSlideArchive/HistomicsUI/commit/819066fd89c0b5c6fa6f1b1bb3fe394fbefa7c42 is a definite improvement.  I still think that if a pixelmap is not visible, then deleting a style shouldn't affect it.  I think that even if the pixel map is in the currently selected annotation, it also shouldn't be affected.

**Comment by naglepuff** [comment]
> https://github.com/DigitalSlideArchive/HistomicsUI/commit/819066fd89c0b5c6fa6f1b1bb3fe394fbefa7c42 is a definite improvement. I still think that if a pixelmap is not visible, then deleting a style shouldn't affect it. I think that even if the pixel map is in the currently selected annotation, it also shouldn't be affected.

Ah. So my initial reasoning for how deletion works here is that if we didn't go through each pixelmap and delete the corresponding category then the style group would  be added back next time any of those pixelmaps are re-drawn, essentially un-deleting it. I though this would be unexpected for users but I can definitely see a strong argument for doing nothing and letting the style group get recreated because then the act of deleting doesn't have inadvertent silent consequences for all pixelmaps.

If the latter is the more correct approach, let me know and I'll take out the changes related to style group deletion.

**Comment by manthey** [comment]
> Ah. So my initial reasoning for how deletion works here is that if we didn't go through each pixelmap and delete the corresponding category then the style group would be added back next time any of those pixelmaps are re-drawn, essentially un-deleting it. I though this would be unexpected for users but I can definitely see a strong argument for doing nothing and letting the style group get recreated because then the act of deleting doesn't have inadvertent silent consequences for all pixelmaps.
> 
> If the latter is the more correct approach, let me know and I'll take out the changes related to style group deletion.

Yes -- for other annotations, removing a style from the style groups does __not__ modify those annotations.  We only want to modify the annotation that we are working on.

I think that we'll still have an existing inconsistency that when we have vector annotations with a style group that isn't in the style list, they don't automatically re-add to the style list and two vector annotations with conflicting properties for the same style group don't harmonize to a single value; but that is an existing issue that we should revisit at a later time.

**Comment by naglepuff** [comment]
11674f2 removes the code that would remove categories/data information from pixelmaps if a style group gets deleted. CI is failing for validation of a test pixelmap annotation, where it wasn't failing for the previous commit. Currently looking into it, looks like its validating against schema without the overlay or pixelmap elements for some reason. Not sure what caused this change

**Review by manthey — APPROVED** [review]
Excellent.  If we change our minds about any behavior, we can revisit it in a different PR.

**Pull request merged**
